server:
  port: 9110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: infrastructure-apigateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.163.168:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务
      routes:
