server:
  port: 9110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: infrastructure-apigateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.163.168:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务
      routes:
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/user/**, /*/cms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-reptile
          uri: lb://service-reptile
          predicates:
            - Path=/*/reptile/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**
        - id: service-tm
          uri: lb://service-tm
          predicates:
            - Path=/*/tm/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**